version: 2.1

orbs:
  heroku: circleci/heroku@7.19.4
workflows:
  heroku_deploy:
    jobs:
      - deploy

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git: # uses default parameters set as Environment Variables in CircleCI build
          only-branch: master
